server:
  port: 30001
spring:
  application:
    name: zj-product
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/zjjz?characterEncoding=utf-8
      username: root
      password: '021033'
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  #SpringMVC上传文件配置
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB
#pagehelper方言配置
pagehelper:
  helper-dialect: mysql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #将自己注册到eureka

MyPicBaseUrl: http://23wz.top:8888/